### ISSUE TITLE
Support for Mocha

### ISSUE THREAD

**Issue by toolmantim** [buildkite/test-collector-javascript#15]

**Comment by clok** [comment]
We would use this at @better

**Comment by mariovisic** [comment]
It seems like mocha may not support having multiple reporters out of the box which may make it a bit tricky.

@clok do you have a way of running multiple reporters on mocha in any of your test suites?

**Comment by mariovisic** [comment]
draft PR up with an implementation #33

**Comment by rmagrin** [comment]
The PR #33 was merged, but the mocha reporter files were not added to the npm package. I create a PR to add them to the npm package: https://github.com/buildkite/test-collector-javascript/pull/45

**Comment by KatieWright26** [comment]
PR #45 was released in #55, version 1.4.2
