### ISSUE TITLE
Support for tagging with prefix or suffix

### ISSUE THREAD

**Issue by CallumHoward** [buildkite/test-collector-javascript#54]
The Ruby collector has the feature to add a prefix or suffix, see [here](https://github.com/buildkite/test-collector-ruby#%EF%B8%8F-tagging-duplicate-test-executions-with-a-prefixsuffix). 

It would be great to have this feature, especially for when support is expanded for Cypress (https://github.com/buildkite/test-collector-javascript/issues/13) and Playwright (https://github.com/buildkite/test-collector-javascript/issues/41).

**Comment by KatieWright26** [comment]
Hi Callum, sorry for the delayed response!
We are working on a tagging solution as a replacement for prefixes  / suffixes, so adding support for them isn't a prioritised piece of work. However, patches are welcome if you would like to make a contribution to test-collector-javascript in the meantime.
