### ISSUE TITLE
Mocha fails to send test results if `--exit` is set

### ISSUE THREAD

**Issue by lox** [buildkite/test-collector-javascript#73]
Spent the past few hours trying to figure out why I wasn't getting test results send to BK, luckily I caught the note about exit in Jest.

Mocha has the same issue! Might be worth calling out in the install instructions? It's a pretty common setting.

**Comment by nprizal** [comment]
Thanks for raising this issue @lox. I can confirm that running Mocha with `--exit` will terminate ongoing processes that attempt to send the test data to Test Analytics.
In case of Jest, the collector will give warning when you try to run it with `--forceExit`. Unfortunately, I can't find a way to read the runner options from Mocha reporter. Adding a note in the README is the least we can do for this. I'll raise this issue internally, and see what we can do.

**Comment by nprizal** [comment]
@lox see #75. This PR should fix the issue when running Mocha with `--exit` option.
