### ISSUE TITLE
Failures in repeatable tests appearing as build failure

### ISSUE THREAD

**Issue by kelly-scalapay** [buildkite/test-collector-javascript#85]
Similar issue to https://github.com/buildkite/test-collector-swift/issues/51

Tests which retry multiple times before passing are causing the overall build within the test analytics summary to show as FAILED.

Is it possible to have the summary page reflect the final state of the build while still collecting the failed test counts and other info?

**Comment by nprizal** [comment]
Hi @kelly-scalapay what test runner are you using? Also, are you using the built-in retry feature provided by the test runner, or is it more like a retry in the CI step? Would be great if you can provide more context.

**Comment by kelly-scalapay** [comment]
Hi @nprizal , I am using [test-collector-javascript](https://github.com/buildkite/test-collector-javascript)

**Comment by laneysmith** [comment]
I am also seeing the same behavior. I'm using `buildkite-test-collector/playwright/reporter` with retries configured via Playwright's `defineConfig`.

**Comment by niceking** [comment]
Hi @laneysmith, could you please provide a link to a build with this behaviour, and also tell us which version of the collector you're using?

**Comment by laneysmith** [comment]
@niceking I was able to reproduce in a sample project using the latest release of the collector v1.7.1:
- Passed build with 1 flakey test: https://buildkite.com/laney-1/playwright-buildkite-test/builds/4#01900967-ecda-4d74-89b1-d92f9d69cc51
- Test analytics run that marked as failed: https://buildkite.com/organizations/laney-1/analytics/suites/playwright-buildkite-test-analytics/runs/5523a53e-8cca-844f-83c2-973f18e4d085

**Comment by niceking** [comment]
Ah, I see. What you're observing is a deliberate design choice in how we surface unreliable runs:

> In Test Analytics, a run is marked as failed as soon as a test execution fails, regardless of whether it passes on a retry. This helps surface unreliable tests. You can have a situation where a build eventually passes on retry in a Pipeline, and the related run is marked as failed in Test Analytics.

You can read more about this [here](https://buildkite.com/docs/test-analytics/test-suites#tracking-reliability). I have passed this feedback onto the team though!

**Comment by laneysmith** [comment]
@niceking I see, I appreciate the clarification. I'm so accustomed to the Cypress Cloud dashboard, where runs with flakey tests that eventually pass on retry are reported as passing, but I see the value in reporting those as failed instead. Thanks!

**Comment by niceking** [comment]
Yeah we totally get it and you're not the first one to raise something like this either 😁 

Sneak peek of potential future UI ideas we may do something like this:
![image (2)](https://github.com/buildkite/test-collector-javascript/assets/4241125/be00b2ed-3a1e-4cf4-83b6-0ff74f43c4bd)
