### ISSUE TITLE
Test reporter upload failure causes test execution failure

### ISSUE THREAD

**Issue by kwonoj** [buildkite/test-collector-javascript#94]
One of the test executions hit 403

```
node:internal/process/promises:391
    triggerUncaughtException(err, true /* fromPromise */);
    ^
AxiosError: Request failed with status code 403
...

data: ***
      message: 'Your organization has reached the usage limits for your plan'
```

and it fails whole test process execution on the CI, makes CI checks failure. Can upload failures be silenced or just show a warning without failing the parent test?

**Comment by nprizal** [comment]
Hi @kwonoj, thanks for opening this issue. I can confirm this issue locally, and agree that this error should be silenced. I'll work on a fix for this.
